# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Build
      run: go build -v -ldflags "-X main.version=$(git describe --tags --always --dirty)" ./...

    - name: Test
      run: go test -v ./...

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v7
      with:
        version: v2.4.0

    - name: Update coverage report
      uses: ncruces/go-coverage-report@v0
      with:
        report: true
        chart: true
        amend: true
      if: |
        github.event_name == 'push'
      continue-on-error: true