# .github/workflows/release.yml
name: goreleaser

on:
  push:
    # run only against tags
    tags:
      - "*"

jobs:
  goreleaser:
    if: ${{ github.actor != 'dependabot[bot]' }}
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build feed-mcp binary for documentation
        run: go build -o feed-mcp main.go

      - name: Generate MCP HTML Documentation for Release
        uses: SPANDigital/mcp-server-dump@main
        with:
          server-command: './feed-mcp run'
          transport: 'command'
          format: 'html'
          output-file: 'mcp-release-docs/index.html'
          scan-tools: 'true'
          scan-resources: 'true'
          scan-prompts: 'true'

      - name: Generate MCP JSON Documentation for Release
        uses: SPANDigital/mcp-server-dump@main
        with:
          server-command: './feed-mcp run'
          transport: 'command'
          format: 'json'
          output-file: 'mcp-release-docs/mcp-schema.json'
          scan-tools: 'true'
          scan-resources: 'true'
          scan-prompts: 'true'

      - name: Generate MCP Markdown Documentation for Release
        uses: SPANDigital/mcp-server-dump@main
        with:
          server-command: './feed-mcp run'
          transport: 'command'
          format: 'markdown'
          output-file: 'mcp-release-docs/README.md'
          scan-tools: 'true'
          scan-resources: 'true'
          scan-prompts: 'true'

      - name: Upload MCP Documentation as Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            mcp-release-docs/index.html
            mcp-release-docs/mcp-schema.json
            mcp-release-docs/README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
